# -*- coding: utf-8 -*-
# Part of Odoo. See LICENSE file for full copyright and licensing details.
{
    'name' : 'School Management',
    'version' : '1.0',
    'summary': 'School Management Software',
    'sequence': 10,
    'description': '"School Management Software"',
    'category': 'Productivity',
    'website': 'https://www.proosoftcloud.com/',
    'depends' : ['mail',
                 'sale',
                 'product',
    ],
    'data': ['security/ir.model.access.csv',
             'data/data.xml',
             'data/school_student.xml',
             'views/student_view.xml',
             'views/parent_view.xml',
             'views/teacher_view.xml',
             'views/configuration_view.xml',
             'views/second_responsible_view.xml',
             'views/product_view.xml',
             'views/program_view.xml',
             'views/attendance_view.xml',
             'views/test_view.xml',
             'views/result_view.xml',
             'views/sale_order_view.xml',
             'views/invoice_view.xml',
             'views/res_partner_view.xml',
             'views/menu.xml'
    ],
    'assets': {
        'web.assets_backend': [
            'school/static/src/components/listView/listView.js',
            'school/static/src/components/listView/listView.xml',
            'school/static/src/components/listView/listView.css',
            'school/static/src/components/example/example.js',
            'school/static/src/components/example/example.xml',
            'school/static/src/components/child/child.js',
            'school/static/src/components/child/child.xml',
        ],
        'web.assets_qweb': [
            'school/static/src/xml/school.xml',
        ],
    },
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}