from . import classe
from . import job
from . import level
from . import parent
from . import school_year
from . import student
from . import subject
from . import teacher
from . import relation
from . import group
from . import civility
from . import family_situation
from . import school_history
from . import school_product
from . import school_attendance
from . import school_test
